YogaMo/YogaMo.Web/Areas/Client/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YogaMo.Web.Helpers;
using YogaMo.WebAPI.Database;

namespace YogaMo.Web.Areas.Client.Controllers
{
    [Area("Client")]
    [Authorization(isClient: true)]
    public class OrdersController : Controller
    {
        private readonly _150222Context _context;

        public OrdersController(_150222Context context)
        {
            _context = context;
        }

        // GET: Client/Orders
        public async Task<IActionResult> Index(OrderStatus? OrderStatus)
        {
            var Client = HttpContext.GetLoggedInClient();

            var query = _context.Order.Include(o => o.Client)
                .Where(x=>x.ClientId == Client.ClientId)
                .OrderByDescending(x=>x.Date)
                .AsQueryable();
            if (OrderStatus != null)
                query = query.Where(x => x.OrderStatus == OrderStatus.Value);

            ViewBag.OrderStatus = OrderStatus;

            return View(await query.ToListAsync());
        }

        // GET: Client/Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Client = HttpContext.GetLoggedInClient();

            var order = await _context.Order
                .Include(o => o.Client)
                .Include(o => o.OrderItem)
                .Include("OrderItem.Product")
                .Where(x=>x.ClientId == Client.ClientId)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        public async Task<IActionResult> CancelOrder(int Id)
        {
            var Order = await _context.Order.FirstOrDefaultAsync(m => m.OrderId == Id);
            if(Order != null && Order.OrderStatus == OrderStatus.Processing)
            {
                Order.OrderStatus = OrderStatus.Canceled;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

YogaMo/YogaMo.Web/Areas/Instructor/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YogaMo.Web.Helpers;
using YogaMo.WebAPI.Database;

namespace YogaMo.Web.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    [Authorization(isInstructor: true)]
    public class OrdersController : Controller
    {
        private readonly _150222Context _context;

        public OrdersController(_150222Context context)
        {
            _context = context;
        }

        // GET: Instructor/Orders
        public async Task<IActionResult> Index(OrderStatus? OrderStatus)
        {
            var query = _context.Order.Include(o => o.Client).OrderByDescending(x=>x.Date).AsQueryable();
            if (OrderStatus != null)
                query = query.Where(x => x.OrderStatus == OrderStatus.Value);

            ViewBag.OrderStatus = OrderStatus;

            return View(await query.ToListAsync());
        }

        // GET: Instructor/Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Client)
                .Include(o => o.OrderItem)
                .Include("OrderItem.Product")
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        public async Task<IActionResult> MarkAsCompleted(int Id)
        {
            var Order = await _context.Order.FirstOrDefaultAsync(m => m.OrderId == Id);
            if(Order != null && Order.OrderStatus == OrderStatus.Confirmed)
            {
                Order.OrderStatus = OrderStatus.Completed;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index), new { OrderStatus = Model.OrderStatus.Confirmed });
        }
        public async Task<IActionResult> CancelOrder(int Id)
        {
            var Order = await _context.Order.FirstOrDefaultAsync(m => m.OrderId == Id);
            if(Order != null && Order.OrderStatus == OrderStatus.Confirmed)
            {
                Order.OrderStatus = OrderStatus.Canceled;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index), new { OrderStatus = Model.OrderStatus.Confirmed });
        }
    }
}

YogaMo/YogaMo.Web/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YogaMo.Web.Helpers;
using YogaMo.Web.ViewModels;
using YogaMo.WebAPI.Database;

namespace YogaMo.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly int MinimumRating = 3;
        private readonly int NumberOfRecommendations = 3;
        public ProductController(_150222Context context, IMapper mapper) : base(context, mapper)
        {
        }

        public IActionResult Index(int Id)
        {
            var Product = _context.Product
                .Where(x => x.ProductId == Id)
                .Include(x=>x.Category)
                .Include(x=>x.Rating)
                .FirstOrDefault();
            if (Product == null)
                return NotFound();

            ProductVM VM = _mapper.Map<ProductVM>(Product);
            VM.AverageRating = Product.Rating.Average(y => (double?)y.Rating1) ?? 0.00;
            VM.Sizes = new List<string> { "S", "M", "L", "XL" };
            VM.Size = "S";
            VM.RecommendedProducts = GetRecommendedProducts(Id);
            VM.ProductsSold = _context.OrderItem.Where(x => x.ProductId == Id && (x.Order.OrderStatus == OrderStatus.Confirmed || x.Order.OrderStatus == OrderStatus.Completed)).Sum(x => x.Quantity);

            return View(VM);
        }


        [Authorization(isClient: true)]
        public IActionResult AddToCart(ProductVM request)
        {
            var CurrentClient = HttpContext.GetLoggedInClient();
            var entity = _mapper.Map<WebAPI.Database.OrderItem>(request);

            var order = _context.Order.Where(x=>x.ClientId == CurrentClient.ClientId && x.OrderStatus == OrderStatus.New).FirstOrDefault();

            var product = _context.Product.Find(request.ProductId);
            if (product == null)
            {
                return new BadRequestObjectResult(new { error = "Product not found" });
            }

            if (entity.Quantity < 0 || product.QuantityStock < entity.Quantity)
            {
                return new BadRequestObjectResult(new { error = "Product not available in requested quantity" });
            }

            if (order != null)
            {
                entity.OrderId = order.OrderId;
            }
            else
            {
                order = new WebAPI.Database.Order
                {
                    ClientId = CurrentClient.ClientId,
                    Date = DateTime.Now,
                    OrderStatus = WebAPI.Database.OrderStatus.New
                };
                _context.Order.Add(order);
                _context.SaveChanges();

                entity.OrderId = order.OrderId;
            }

            entity.Product = product;
            entity.Price = product.Price;

            _context.OrderItem.Add(entity);
            _context.SaveChanges();

            var TotalPrice = _context.OrderItem.Where(x => x.OrderId == order.OrderId).Sum(x => x.Price * x.Quantity);
            order.TotalPrice = TotalPrice;
            _context.SaveChanges();

            TempData["Success"] = "Added To Cart: <b>" + product.Name + "</b> (" + request.Quantity + "x)";

            return Ok();
        }

        [Authorization(isClient: true)]
        public IActionResult BuyNow(ProductVM request)
        {
            var CurrentClient = HttpContext.GetLoggedInClient();
            var entity = _mapper.Map<WebAPI.Database.OrderItem>(request);

            var order = _context.Order.Where(x=>x.ClientId == CurrentClient.ClientId && x.OrderStatus == OrderStatus.New).FirstOrDefault();

            var product = _context.Product.Find(request.ProductId);
            if (product == null)
            {
                return new BadRequestObjectResult(new { error = "Product not found" });
            }

            if (entity.Quantity < 0 || product.QuantityStock < entity.Quantity)
            {
                return new BadRequestObjectResult(new { error = "Product not available in requested quantity" });
            }

            if (order != null)
            {
                entity.OrderId = order.OrderId;
            }
            else
            {
                order = new WebAPI.Database.Order
                {
                    ClientId = CurrentClient.ClientId,
                    Date = DateTime.Now,
                    OrderStatus = WebAPI.Database.OrderStatus.New
                };
                _context.Order.Add(order);
                _context.SaveChanges();

                entity.OrderId = order.OrderId;
            }

            entity.Product = product;
            entity.Price = product.Price;

            _context.OrderItem.Add(entity);
            _context.SaveChanges();

            var TotalPrice = _context.OrderItem.Where(x => x.OrderId == order.OrderId).Sum(x => x.Price * x.Quantity);
            order.TotalPrice = TotalPrice;
            _context.SaveChanges();

            TempData["Success"] = "Added To Cart: <b>" + product.Name + "</b> (" + request.Quantity + "x)";

            return Ok();
        }

        public IActionResult RateProduct(int Id, int rating)
        {
            var Client = HttpContext.GetLoggedInClient();

            if(!_context.OrderItem.Any(x=>x.ProductId == Id && x.Order.ClientId == Client.ClientId && x.Order.OrderStatus == OrderStatus.Completed))
            {
                TempData["Error"] = "You cannot rate a product you have not bought.";
                return RedirectToAction(nameof(Index), new { Id });
            }

            var entity = _context.Rating.Where(x => x.ProductId == Id && x.ClientId == Client.ClientId).FirstOrDefault();
            if (entity != null)
            {
                entity.Rating1 = rating;
            }
            else
            {
                entity = new Rating
                {
                    ClientId = Client.ClientId,
                    ProductId = Id,
                    Rating1 = rating
                };

                _context.Rating.Add(entity);
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Index), new { Id });
        }

        public List<Model.Product> GetRecommendedProducts(int ProductIdToExclude)
        {
            int ClientId = HttpContext.GetLoggedInClient()?.ClientId ?? 0;
            if (ClientId != 0)
            {
                List<Rating> ListOfRatings = _context.Rating.Where(x => x.ClientId == ClientId)
                    .Include(m => m.Product.Category)
                    .ToList();

                List<Rating> ListOfPositiveRatings = ListOfRatings
                    .Where(x => x.Rating1 >= MinimumRating)
                    .ToList();

                if (ListOfPositiveRatings.Count() > 0)
                {
                    List<Category> uniqueCategories = new List<Category>();
                    foreach (var Rating in ListOfPositiveRatings)
                    {
                        bool add = true;
                        for (int i = 0; i < uniqueCategories.Count; i++)
                        {
                            if (Rating.Product.CategoryId == uniqueCategories[i].CategoryId)
                            {
                                add = false;
                            }
                        }

                        if (add)
                        {
                            uniqueCategories.Add(Rating.Product.Category);
                        }
                    }

                    List<Product> ListOfRecommendedProducts = new List<Product>();
                    foreach (var Category in uniqueCategories)
                    {
                        var ProductsInCategory = _context.Product
                            .Where(x => x.QuantityStock > 0)
                            .Where(x => x.ProductId != ProductIdToExclude)
                            .Where(n => n.CategoryId == Category.CategoryId)
                            .Include(x => x.Category)
                            .ToList();

                        foreach (var Product in ProductsInCategory)
                        {
                            bool add = true;
                            for (int i = 0; i < ListOfRecommendedProducts.Count; i++)
                            {
                                if (Product.ProductId == ListOfRecommendedProducts[i].ProductId)
                                {
                                    add = false;
                                }
                            }

                            foreach (var Rating in ListOfRatings)
                            {
                                if (Product.ProductId == Rating.ProductId)
                                {
                                    add = false;
                                }
                            }

                            if (add)
                            {
                                ListOfRecommendedProducts.Add(Product);
                            }
                        }
                    }

                    if (ListOfRecommendedProducts.Count > 0)
                    {
                        var list1 = _mapper.Map<List<Model.Product>>(ListOfRecommendedProducts);

                        foreach (var entity in list1)
                        {
                            entity.AverageRating = _context.Rating.Where(x => x.ProductId == entity.ProductId).Average(x => (double?)x.Rating1) ?? 0;
                        }

                        list1 = list1.OrderByDescending(x => x.AverageRating).Take(NumberOfRecommendations).ToList().OrderBy(x => Guid.NewGuid()).ToList();

                        return list1;
                    }
                }
            }

            var ListOfAllProducts = _context.Product

YogaMo/YogaMo.Web/Areas/Instructor/Views/Orders/Details.cshtml
@model YogaMo.WebAPI.Database.Order

@{
    ViewData["Title"] = "Order Details - #" + Model.OrderId;
}

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class="col-sm-10">
            $@Model.TotalPrice.ToString("0.00")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Client.Email)
        </dd>
    </dl>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Product
                </th>
                <th>
                    Price
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Total Price
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderItem)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product.Name)
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        $@(item.Quantity * item.Price)
                    </td>
                    <td>
                        <a class="btn btn-teal" asp-area="" asp-controller="Product" asp-action="Index" asp-route-id="@item.ProductId">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
<div>
    @if (Model.OrderStatus == YogaMo.WebAPI.Database.OrderStatus.Confirmed)
    {

        <a asp-action="MarkAsCompleted" asp-controller="Orders" asp-route-id="@Model.OrderId" class="btn btn-success">Mark as Completed</a> @Html.Raw("&nbsp;")
        <a asp-action="CancelOrder" asp-route-id="@Model.OrderId" class="btn btn-danger">Cancel Order</a> @Html.Raw("&nbsp;")
    }
    <a asp-action="Index" class="btn btn-teal">Back to List</a>
</div>

YogaMo/YogaMo.Web/Areas/Instructor/Views/Orders/Index.cshtml
@model IEnumerable<YogaMo.WebAPI.Database.Order>

@{
    ViewData["Title"] = "Orders";
    var OrderStatusList = Html.GetEnumSelectList<YogaMo.WebAPI.Database.OrderStatus>();
    var OrderStatus = ViewBag.OrderStatus as YogaMo.WebAPI.Database.OrderStatus?;
}

@section SearchArea {
    <div class="card">
        <div class="card-body">
            <h4>
                Filter orders
            </h4>
            <form method="get" class="d-inline-block col-md-4">
                <select name="OrderStatus" class="form-control col-md-9 d-inline-block" onchange="this.form.submit();">
                    <option value="">All orders</option>
                    @foreach (var item in OrderStatusList)
                    {
                        if (OrderStatus != null && int.Parse(item.Value) == (int)OrderStatus.Value)
                        {
                            <option value="@item.Value" selected>@item.Text</option>
                        }
                        else
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    }
                </select><div class="col-md-3 d-inline-block align-top">
                    <button class="btn btn-primary w-100" hidden>Search</button>
                </div>
            </form>
        </div>
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    $@item.TotalPrice.ToString("0.00")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Client.FullName)
                </td>
                <td>
                    @if (item.OrderStatus == YogaMo.WebAPI.Database.OrderStatus.Confirmed)
                    {
                        <a asp-action="Details" asp-route-id="@item.OrderId" class="btn btn-teal">Manage Order</a>
                    }
                    else
                    {
                        <a asp-action="Details" asp-route-id="@item.OrderId" class="btn btn-teal">Order Details</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>